# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ac3ef87f7d2a828120818e42ce1ced6c"
name = "Hsx2 Developer"
handle = "hsx2-developer-1"
application_url = "https://males-fleece-issued-cgi.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hsx2coder.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://males-fleece-issued-cgi.trycloudflare.com/auth/callback",
  "https://males-fleece-issued-cgi.trycloudflare.com/auth/shopify/callback",
  "https://males-fleece-issued-cgi.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
