# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f1dd805da549fd386ed18537961ea0c6"
name = "Hsx2 Developer"
handle = "hsx2-developer"
application_url = "https://beverage-biology-relationships-fingers.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hsx2coder.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://beverage-biology-relationships-fingers.trycloudflare.com/auth/callback",
  "https://beverage-biology-relationships-fingers.trycloudflare.com/auth/shopify/callback",
  "https://beverage-biology-relationships-fingers.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
